### ISSUE TITLE
Keep line length under 120 characters

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#11]
While lambda method implementations are nice, longer lines tend to become somewhat unreadable. For example, in [TreeBuilderContext](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Core/Trees/TreeBuilderContext.cs), we have lines with 200 characters which are stretching the readability of the document.

As a rule of thumb, I would suggest to keep lines under 120 characters. This limit is large enough to make the most of the bigger screens that we have, but without hurting the readability. Plus, on website like GitHub itself, characters beyond 120 are simply not even visible on screen without horizontal scrolling. Thanks!

**Comment by allisterb** [comment]
I'll shorten the lines in each source file to max 120 chars as I work on them.

**Comment by vermorel** [comment]
Closing spike 2 tickets.
