### ISSUE TITLE
Intent of the GenericMath class?

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#12]
I have posted a list of remarks for the [commit that introduces `GenericMath.cs`](https://github.com/Lokad/Adrien/commit/bd5f63b98634b20352f0a9f6e3c0f0443155d0f5#diff-8725435ec4eb57f540c38159ac318abcR17) however, I am not too sure about the intent associated with the design of this class. Indeed, some functions like `Sqrt()` are merely special case of more general method like `F()`. Before jumping into "fixing" the issue that I am pointing out, it would be better to clarify the intent, in order to assess whether the design is relevant or not. Thanks!

**Comment by allisterb** [comment]
`GenericMath` provides methods for working with numeric values in generic classes like `Var<T>` where the concrete type isn't known up-front e.g. `INDArray` defines a Random() method that `Var<T>` must implement that fills the array buffer with random values.

**Comment by vermorel** [comment]
Closing spike 2 tickets.
