### ISSUE TITLE
Removing 'BOOLEAN' from 'DataType'

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#14]
The `BOOLEAN` case in [DataType](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Base/Compiler/DataType.cs) is a bit off. As it's not a numerical type, it will require a lot of special casing pretty much every where. Then, as I am not too sure if there is any use case that support this data type, it feels that we could simplify the whole framework by eliminating this case.

**Comment by allisterb** [comment]
I had thought of use cases of huge Tensors with just binary 0 or 1 as the values when working with logic equations and circuits and things like that, but using byte or another numeric type is probably more sensible in those cases.

**Comment by vermorel** [comment]
Having logic network of pure bits may indeed be a use case, but I suspect that such networks would be built on top of `byte` or `ulong` (or even something more dynamic), with the necessary plumbing on top. For now, I would still suggest to not deal with `BOOLEAN`. If really needed, it can still be re-introduced later on.
