### ISSUE TITLE
IShape.Stride should be an array

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#16]
Reading the [Numpy doc on strides](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ndarray.strides.html#numpy.ndarray.strides), it looks like the _strides_ should be a vector that has a length equal to the rank of the tensor. PlaidML is taking a similar approach, but going a bit further with a [TensorDimention](https://github.com/plaidml/plaidml/blob/52a4c8b27417a0da76f264c4cc265fd868858603/tile/lang/shape.h#L123) that packs both the dimension and the stride. Thus, `int IShape.Stride` should probably be rewritten as `int[] IShape.Strides`.

However, I am wondering whether PlaidML is not an even better solution: to introduce a `TensorDimension(int, int)` struct that represent both the dimension and stride.

**Comment by allisterb** [comment]
The [Dimension](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Core/Notation/Dimension.cs) class represents a single tensor dimension with length, stride.

**Comment by vermorel** [comment]
Closing spike 2 tickets.
