### ISSUE TITLE
ReportApiCallError() should be replaced by exceptions

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#21]
The pattern of `ReportApiCallError()` is used in a lot of places in `Adrien.Compiler.PlaidML`. It looks to me that throwing exception would be the more proper way of handling those situations. I might be missing something though, but right now, we end-up with a lot of code that looks very odd from a .NET perspective (ex: failed constructors that still returns the object).

**Comment by allisterb** [comment]
ReportApiCallError() just logs the last PlaidML API error status and message, but failures allocating PlaidML objects now also throw `PlaidMLApiException`s.
