### ISSUE TITLE
Lightweight Ndarray

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#3]
I suggest to introduce a lightweight [Ndarray](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.ndarray.html) implementation named `Ndarray`. See also [Tensor.cs](https://github.com/alex-weaver/TensorSharp/blob/master/src/TensorSharp/Tensor.cs)

A few remarks:

* Let's stick to the Numpy terminology (might facilitate interop)
* For the `shape`, we only need `Int32`; does not make sense to manipulate bigger tensors.

I suggest to limit the C# logic to the plain indexing of the Ndarray.

**Comment by allisterb** [comment]
We could have an interface `INdarray` which is inherited by an abstract `Ndarray` class and optionally fixed dimension arrays like `4darray`. We will use the .NET Core `Memory<T>`, `Span<T>` [et.al](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx) which provides memory management and things like pooling for managed and unmanaged memory. The actual memory storage object will be a `struct` to interface with C/C++ libraries.

Ndaarrays will follow the Numpy Ndarray memory layout. The `Tensor` class will inherit from `Ndarray` and implement any required tensor interfaces. There are different Tensor interfaces e.g Facebook TC requires in-memory tensors to support the DLPack interface. It's relatively simple:

```
*!
 * \brief Plain C Tensor object, does not manage memory.
 */
typedef struct {
  /*!
   * \brief The opaque data pointer points to the allocated data.
   *  This will be CUDA device pointer or cl_mem handle in OpenCL.
   *  This pointer is always aligns to 256 bytes as in CUDA.
   */
  void* data;
  /*! \brief The device context of the tensor */
  DLContext ctx;
  /*! \brief Number of dimensions */
  int ndim;
  /*! \brief The data type of the pointer*/
  DLDataType dtype;
  /*! \brief The shape of the tensor */
  int64_t* shape;
  /*!
   * \brief strides of the tensor,
   *  can be NULL, indicating tensor is compact.
   */
  int64_t* strides;
  /*! \brief The offset in bytes to the beginning pointer to data */
  uint64_t byte_offset;
} DLTensor;
```

**Comment by allisterb** [comment]
Alex Weaver's TensorSharp library supports different memory locations (CPU/GPU) and different devices for operations and also has support for implementing [tensor expressions](https://github.com/allisterb/TensorSharp/blob/master/src/TensorSharp/Expression/TExpression.cs)

I looked at this and also Microsoft's tensor implementation and I think TensorSharp is better suited for Adrien as it is very extendable and has implemented a lot of functionality we need. I forked Alex's project and created a .NET Standard project that we will use as a base for Adrien.

**Comment by vermorel** [comment]
I suggest to keep really separate the tensor expression (plain logical tree) from their numerical counterpart. If `Evaluate()` is bundled with the tensor expression, then it limits our options to plug multiple implementation (SIMD / GPU / TPU / etc).

**Comment by allisterb** [comment]
I implemented the PlaidML low-level API as the first Adrien [backend/compiler](https://github.com/Lokad/Adrien/tree/master/src/spikes/2/Adrien.Compiler.PlaidML) and I've been working with the PlaidML tensor API for a few days. They have a nice decoupling between a tensor's shape, a device buffer (CPU/GPU), and a tensor memory view which is the only place memory is actually allocated for a tensor. I think following this API design will allow the Adrien tensor iimplementation to be flexible enough to support multiple tensor algebra compilers and device back-ends as well as being able to support different tensor interfaces like DLPack.

Logically and in real terms an Adrien tensor expression is separate from a tensor binding which binds allocated memory on a hardware device to a tensor variable declared by a tensor expression. A tensor comprehension is thus the combination of a tensor expression and the tensor variable bindings to memory.

**Comment by allisterb** [comment]
[Var](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Core/Compiler/Var.cs) instances are variables that bind tensor declarations to data stored in memory. Var implements [INDArray](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Base/Compiler/INDArray.cs) 
which is is an interface that contains Numpy-like methods for working with tensor variables. These methods can live alongside and be aliases of more C# oriented methods, so users coming from NumPy have a familiar set of operations to work with tensor data.

**Comment by allisterb** [comment]
`INDArray` will implement Numpy compatible methods and properties. On the front-end side `Var<T>` [implements ](https://github.com/Lokad/Adrien/blob/master/src/spikes/2/Adrien.Core/Compiler/Var.cs)this interface.
