### ISSUE TITLE
Tensor expressions

### ISSUE THREAD

**Issue by vermorel** [Lokad/Adrien#4]
As outlined in the [prototype spec](https://github.com/Lokad/Adrien/blob/master/docs/front-end-cshap-api-proposal-1.md), I suggest to introduce _tensor expressions_; which would be the .NET flavor of the Facebook Tensor Comprehensions, or the PlaidML Tiles, or the TVM Tensor Index Expression Description Language.

Those tensor expressions are intended to be compiled into functions `Ndarray* -> Ndarray*`; also, I would suggest to isolate the compiler logic, in order to support multiple implementations, ranging from non-optimized fully managed ones to highly optimized GPU-backed ones.

**Comment by vermorel** [comment]
I like this approach leveraging the recent `out` inline declaration of variables. Very cool!

**Comment by allisterb** [comment]
Tensor expressions are implemented by [Notation](https://github.com/Lokad/Adrien/tree/master/src/spikes/2/Adrien.Core/Notation) classes like `TensorExpression`, `Index`, `TensorOperation` which are translated into `ExpressionTree`s that are used by tensor algebra compilers to generate code to execute the tensor operations.
